# Generated by Django 4.1.1 on 2022-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер вагона')),
                ('home_enterprise', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предприятия приписки')),
                ('wagon_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип вагона')),
                ('construction_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('building_plant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Завод постройки')),
                ('state_of_use', models.CharField(blank=True, max_length=100, null=True, verbose_name='Состояние использования')),
                ('date_to_z', models.DateField(blank=True, null=True, verbose_name='Дата ТО-З')),
                ('last_dr', models.DateField(blank=True, null=True, verbose_name='последний ДР')),
                ('last_kr_1', models.DateField(blank=True, null=True, verbose_name='последний КР-1')),
                ('last_kr_2', models.DateField(blank=True, null=True, verbose_name='последний КР-2')),
                ('last_kvr', models.DateField(blank=True, null=True, verbose_name='последний КВР')),
                ('assigned_service_life', models.PositiveIntegerField(blank=True, null=True, verbose_name='Назначенный срок службы')),
                ('service_life', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок службы')),
                ('planned_write_of_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата списания')),
                ('wagon_model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Модель вагона')),
                ('wagon_tare', models.FloatField(blank=True, null=True, verbose_name='Тара вагона')),
                ('body_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид окраски кузова')),
                ('sleeping_place_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество спальных мест')),
                ('sitting_place_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество мест для сидения')),
                ('far_and_air_condition_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Система вентиляции и кондиционеров')),
                ('generator_type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Тип генератора')),
                ('generator_drive_design', models.CharField(blank=True, max_length=60, null=True, verbose_name='Конструкция привода генератора')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагоны',
            },
        ),
    ]
