# Generated by Django 4.1.1 on 2022-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertrack',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер вагона'),
        ),
    ]
