# Generated by Django 4.1.1 on 2022-09-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_manage', '0002_alter_passengertrack_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengertrack',
            options={'ordering': ('id',), 'verbose_name': 'Вагон', 'verbose_name_plural': 'Вагоны'},
        ),
    ]
