# Generated by Django 4.1.1 on 2022-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_manage', '0003_alter_passengertrack_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Название файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
            ],
        ),
    ]
