# Generated by Django 4.1.1 on 2022-12-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_manage', '0004_excelfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFiles',
        ),
    ]
